### ISSUE TITLE
Failed build  'cannot find -lwallet_merged2'

### ISSUE THREAD

**Issue by vdo** [mbg033/monero-core#43]
When building on Void Linux, with all dependencies installed, the build fails at the final step with

```
g++ -Wl,-O1 -Wl,-rpath,/usr/lib -o release/bin/monero-core main.o filter.o clipboardAdapter.o oscursor.o WalletManager.o Wallet.o PendingTransaction.o TransactionHistory.o TransactionInfo.o oshelper.o TranslationManager.o qrc_qml.o moc_filter.o moc_clipboardAdapter.o moc_oscursor.o moc_WalletManager.o moc_Wallet.o moc_PendingTransaction.o moc_TransactionHistory.o moc_TransactionInfo.o moc_oshelper.o moc_TranslationManager.o   -L/home/vdo/src/monero-core/bitmonero/lib -lwallet_merged -lwallet_merged2 -Wl,-Bstatic -lboost_serialization -lboost_thread -lboost_system -lboost_date_time -lboost_filesystem -lboost_regex -lboost_chrono -lboost_program_options -lssl -lcrypto -Wl,-Bdynamic -ldl -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld: cannot find -lwallet_merged2
collect2: error: ld returned 1 exit status
```

complete log:
https://paste.fedoraproject.org/413036/

**Comment by medusadigital** [comment]
can confirm, same issue on ubuntu 16.04 with same dependencies as always. must have happend with latest commit

**Comment by mbg033** [comment]
Sorry, didn't checked with clean build.
This happened after I rebased my bitmonero fork with bitmonero upstream,
Problem is something in wallet_merged (that comes from bitmonero) depends on libunbound and libunbound was repacked as wallet_merged2 in order to not introduce new dependencies for gui app (yes it's hackish).
"hack" was removed in commit:
https://github.com/monero-project/bitmonero/commit/8bed9a42f7102fd6f49414e3740cbe291cb9a30c#diff-79e81b971acdd65f07b8f8bf8c0fdb6b

will try to find better solution. any advises are welcome

**Comment by medusadigital** [comment]
[19:05:00] moneromooo: I'd kick the wallet_merged\* libs out and just link normally to whatever libs are needed.

**Comment by mbg033** [comment]
Yep, make sense, as wallet_merged is huge and linking  takes some time.
For now I temporary reverted that commit in my bitmonero develop branch, pointed "get_libwallet_api.sh" to this branch so app can be build. Will arrange it properly later - I'll be travelling for few days.

**Comment by medusadigital** [comment]
ok it now builds successfully, thank you!

i had to edit the conf file in ~/.config/The Monero Project so it points to ~/Monero Accounts/1st account so i could open the wallet but after that all went fine.

save travells

**Comment by vdo** [comment]
Solved now
