### ISSUE TITLE
Error Message When Running Monero Core GUI

### ISSUE THREAD

**Issue by phloatingman** [mbg033/monero-core#53]
I created a private testnet, mined 60 blocks, and successfully transferred between two simplewallets.

I'd like to transfer from a simplewallet to the monero core gui wallet for testing purposes.  

When I launch monero-core it says "Connected" under "Network status".  However, when I try to transfer from simplewallet to monero-core wallet the balance remains 0 in monero-core wallet even after 6 blocks confirmed the transaction in simplewallet.

In the terminal, it says this...

`ERROR /home/administrator/monero-core/bitmonero/src/wallet/wallet2.cpp:780 res.blocks.size() != res.output_indices.size(). THROW EXCEPTION: error::wallet_internal_error`

Can anyone point me in the right direction?

**Comment by medusadigital** [comment]
Hi phloatingman,

You should be able to see more details when watching the monerod log with set_log 2 when trying to send coins.

due to the mandatory mixing, i found normal public testnet much more easy to test (since on private testnet you will maybe not find enough inputs to mix with sometimes)

it should work with current public testnet (which is allready on fork v5, so minimum mixing is 4)

GUI should be able to connect to daemon whenrun with --testnet --testnet-rpc-bind-port 38081

**Comment by phloatingman** [comment]
Thanks medusdigital.  You were right.  After I got the private testnet to work with gui it is difficult to find enough mixins.

I tried connecting the daemon to public testnet, but now a new error appears...

`Failed to connect to any of seed peers, continuing without seeds`

I opened a new issue for that here...
https://github.com/monero-project/monero/issues/1078
